Html Lang selection
dewsign/nova-pages pull request #26
Opened 2019-11-08 10:23 UTC by crumb1e

Add functionality to enable the customisation of the html lang tag on creation of a page.

2019-11-12 10:02 UTC, m2de requested changes
Great work, just a few tweaks. Thanks @crumb1e

2019-11-12 10:02 UTC, m2de commented on src-php/Database/migrations/2019_11_06_000000_update_pages_table_add_language.php
> +            $table->string('language')->default('gb')->after('template');
Would be nice to make this use the default language from the config

2019-11-12 10:02 UTC, m2de commented on src-php/Nova/Page.php
> +            Select::make('Language (English by default)', 'language')
Please can we make this a localised string

2019-11-12 10:02 UTC, m2de commented on src-php/Nova/Page.php
> +            Select::make('Language (English by default)', 'language')
And it isn't english by default. That is configurable. If we want to show that message it needs to actually look up the set default.

2019-11-12 10:02 UTC, m2de commented on src-php/NovaPages.php
> +            return Str::title($item);
Please localise `$item`

2019-11-12 10:02 UTC, m2de commented on src-php/Config/novapages.php
> +        'en' => 'english'
Please use correct capitalisation for languages and drop the Str:: helper in the code.

2019-11-13 09:24 UTC, m2de requested changes
Just a couple of minor tweaks, but this is looking great, thanks @crumb1e

2019-11-13 09:24 UTC, m2de commented on src-php/Config/novapages.php
> +        'en-GB' => 'English'
Need to add this to the docs please

2019-11-13 09:24 UTC, m2de commented on src-php/Models/Page.php
> +        } else {
No need for an else here, but matters not.

2019-11-13 10:21 UTC, crumb1e commented
@m2de Ready for you to have another look pal

2019-11-13 10:49 UTC, m2de approved these changes

2019-11-13 10:53 UTC, merged